#!/bin/bash
# EVA-01 - Installation Script
# Creates wrapper scripts that call Python modules using the project's uv environment

set -e

# Configuration
INSTALL_DIR="$HOME/.local/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
PY_MODULE_DIR="$PROJECT_DIR/src/eva_01"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    local level=$1
    local message=$2
    local color=""

    case $level in
        "INFO")  color=$BLUE ;;
        "WARN")  color=$YELLOW ;;
        "ERROR") color=$RED ;;
        "SUCCESS") color=$GREEN ;;
    esac

    echo -e "${color}[$(date '+%H:%M:%S')] [$level] $message${NC}"
}

# Check dependencies
check_dependencies() {
    log "INFO" "Checking dependencies..."

    # Check uv
    if ! command -v uv &> /dev/null; then
        log "ERROR" "uv not found. Install with: curl -LsSf https://astral.sh/uv/install.sh | sh"
        exit 1
    fi
    log "INFO" "Found uv: $(uv --version)"

    # Check Python via uv
    if ! uv run python3 --version &> /dev/null 2>&1; then
        log "INFO" "Initializing uv environment..."
        cd "$PROJECT_DIR"
        uv sync
    fi

    local python_version=$(cd "$PROJECT_DIR" && uv run python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    log "INFO" "Found Python $python_version (via uv)"

    # Check Claude Code CLI (optional)
    if ! command -v claude &> /dev/null; then
        log "WARN" "Claude Code CLI not found"
        log "INFO" "Install with: npm install -g @anthropic-ai/claude-code"
    else
        log "INFO" "Claude Code CLI found"
    fi

    log "SUCCESS" "Dependencies check passed"
}

# Verify project structure
verify_project() {
    log "INFO" "Verifying project structure..."

    if [[ ! -f "$PY_MODULE_DIR/spec_to_prd.py" ]]; then
        log "ERROR" "spec_to_prd.py not found at $PY_MODULE_DIR"
        exit 1
    fi

    if [[ ! -f "$PY_MODULE_DIR/impl_prd.py" ]]; then
        log "ERROR" "impl_prd.py not found at $PY_MODULE_DIR"
        exit 1
    fi

    if [[ ! -f "$PY_MODULE_DIR/observe_impl.py" ]]; then
        log "ERROR" "observe_impl.py not found at $PY_MODULE_DIR"
        exit 1
    fi

    if [[ ! -f "$PROJECT_DIR/pyproject.toml" ]]; then
        log "ERROR" "pyproject.toml not found at $PROJECT_DIR"
        exit 1
    fi

    log "SUCCESS" "Project structure verified"
}

# Create installation directory
create_install_dir() {
    log "INFO" "Creating installation directory..."
    mkdir -p "$INSTALL_DIR"
    log "SUCCESS" "Directory created: $INSTALL_DIR"
}

# Create command wrapper scripts
create_commands() {
    log "INFO" "Creating command scripts..."

    # Create spec-to-prd command
    cat > "$INSTALL_DIR/spec-to-prd" << EOF
#!/bin/bash
# spec-to-prd: Convert spec markdown files to PRD JSON format
# Auto-generated by install.sh - DO NOT EDIT
# Project: $PROJECT_DIR

# Add eva_01 module to PYTHONPATH so Python can import it
export PYTHONPATH="$PY_MODULE_DIR:\$PYTHONPATH"

# Activate uv virtual environment and run (keeps current working directory)
source "$PROJECT_DIR/.venv/bin/activate"
exec python3 "$PY_MODULE_DIR/spec_to_prd.py" "\$@"
EOF

    # Create impl-prd command
    cat > "$INSTALL_DIR/impl-prd" << EOF
#!/bin/bash
# impl-prd: Autonomous loop to implement PRD user stories
# Auto-generated by install.sh - DO NOT EDIT
# Project: $PROJECT_DIR

# Add eva_01 module to PYTHONPATH so Python can import it
export PYTHONPATH="$PY_MODULE_DIR:\$PYTHONPATH"

# Activate uv virtual environment and run (keeps current working directory)
source "$PROJECT_DIR/.venv/bin/activate"
exec python3 "$PY_MODULE_DIR/impl_prd.py" "\$@"
EOF

    # Create observe-impl command
    cat > "$INSTALL_DIR/observe-impl" << EOF
#!/bin/bash
# observe-impl: Analyze impl-prd session logs and report issues
# Auto-generated by install.sh - DO NOT EDIT
# Project: $PROJECT_DIR

# Add eva_01 module to PYTHONPATH so Python can import it
export PYTHONPATH="$PY_MODULE_DIR:\$PYTHONPATH"

# Activate uv virtual environment and run (keeps current working directory)
source "$PROJECT_DIR/.venv/bin/activate"
exec python3 "$PY_MODULE_DIR/observe_impl.py" "\$@"
EOF

    # Make executable
    chmod +x "$INSTALL_DIR/spec-to-prd"
    chmod +x "$INSTALL_DIR/impl-prd"
    chmod +x "$INSTALL_DIR/observe-impl"

    log "SUCCESS" "Commands created in $INSTALL_DIR"
}

# Create uninstall script
create_uninstall_script() {
    log "INFO" "Creating uninstall script..."

    cat > "$PROJECT_DIR/uninstall.sh" << 'UNINSTALL_EOF'
#!/bin/bash
# EVA-01 - Uninstall Script

set -e

INSTALL_DIR="$HOME/.local/bin"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    local level=$1
    local message=$2
    local color=""
    case $level in
        "INFO")  color=$BLUE ;;
        "ERROR") color=$RED ;;
        "SUCCESS") color=$GREEN ;;
    esac
    echo -e "${color}[$(date '+%H:%M:%S')] [$level] $message${NC}"
}

log "INFO" "Uninstalling EVA-01..."

# Remove command scripts
if [[ -f "$INSTALL_DIR/spec-to-prd" ]]; then
    rm -f "$INSTALL_DIR/spec-to-prd"
    log "INFO" "Removed $INSTALL_DIR/spec-to-prd"
fi

if [[ -f "$INSTALL_DIR/impl-prd" ]]; then
    rm -f "$INSTALL_DIR/impl-prd"
    log "INFO" "Removed $INSTALL_DIR/impl-prd"
fi

if [[ -f "$INSTALL_DIR/observe-impl" ]]; then
    rm -f "$INSTALL_DIR/observe-impl"
    log "INFO" "Removed $INSTALL_DIR/observe-impl"
fi

log "SUCCESS" "EVA-01 uninstalled successfully!"
echo ""
echo "Note: The project directory and uv environment are preserved."
echo "To fully remove, delete the project directory manually."
UNINSTALL_EOF

    chmod +x "$PROJECT_DIR/uninstall.sh"
    log "SUCCESS" "Uninstall script created: $PROJECT_DIR/uninstall.sh"
}

# Check PATH
check_path() {
    log "INFO" "Checking PATH configuration..."

    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        log "WARN" "$INSTALL_DIR is not in your PATH"
        echo ""
        echo "Add this to your ~/.bashrc, ~/.zshrc, or ~/.profile:"
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo ""
        echo "Then run: source ~/.bashrc (or restart your terminal)"
        echo ""
    else
        log "SUCCESS" "$INSTALL_DIR is already in PATH"
    fi
}

# Show help
show_help() {
    cat << HELP_EOF
EVA-01 Installation Script

Usage: $0 [COMMAND]

Commands:
    install     Install PRD Loop globally (default)
    --help      Show this help message

This script creates wrapper scripts in ~/.local/bin that call the Python
modules using the project's uv environment at:
    $PROJECT_DIR

After installation, the following commands are available:
    spec-to-prd     Convert spec markdown files to PRD JSON
    impl-prd        Autonomous loop to implement PRD stories
    observe-impl    Analyze session logs and report issues

To uninstall, run:
    $PROJECT_DIR/uninstall.sh

Quick Start:
    1. cd your-project
    2. spec-to-prd your-spec.md     # Convert spec to PRD (auto-init .prd)
    3. impl-prd                     # Start implementation loop

HELP_EOF
}

# Main installation
main() {
    echo ""
    log "INFO" "Installing EVA-01..."
    log "INFO" "Project directory: $PROJECT_DIR"
    echo ""

    check_dependencies
    verify_project
    create_install_dir
    create_commands
    create_uninstall_script
    check_path

    echo ""
    log "SUCCESS" "EVA-01 installed successfully!"
    echo ""
    echo "Commands installed:"
    echo "  spec-to-prd --help    Show spec-to-prd options"
    echo "  impl-prd --help       Show impl-prd options"
    echo "  observe-impl --help   Show observe-impl options"
    echo ""
    echo "To uninstall:"
    echo "  $PROJECT_DIR/uninstall.sh"
    echo ""
    echo "Quick start:"
    echo "  1. cd your-project"
    echo "  2. spec-to-prd your-spec.md"
    echo "  3. impl-prd"
    echo ""

    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        log "WARN" "Don't forget to add $INSTALL_DIR to your PATH"
    fi
}

# Handle command line arguments
case "${1:-install}" in
    install)
        main
        ;;
    --help|-h|help)
        show_help
        ;;
    *)
        echo "Unknown command: $1"
        echo "Use --help for usage information"
        exit 1
        ;;
esac
